from sqlalchemy import Column, String, Boolean, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from app.models.base import Base, UUIDMixin, TimestampMixin


class CrossPillarInsight(Base, UUIDMixin, TimestampMixin):
    """A recommendation generated by correlating real data across two or
    more pillars (e.g. a crop diagnosis + a nearby dry borehole). Every
    insight here is derived from actual rows in other tables at generation
    time — nothing here is a canned or fabricated recommendation."""
    __tablename__ = "cross_pillar_insights"
    user_id        = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)  # null = district-wide
    district       = Column(String(100), nullable=False, index=True)
    source_pillar  = Column(String(30), nullable=False)   # e.g. 'zunde', 'mvura'
    target_pillar  = Column(String(30), nullable=False)   # e.g. 'simba', 'zunde'
    insight_type   = Column(String(60), nullable=False)   # e.g. 'drought_water_risk'
    severity       = Column(String(20), default="info")   # info | amber | red
    message        = Column(Text, nullable=False)
    dismissed      = Column(Boolean, default=False)
