"""add cross_pillar_insights table

Revision ID: fd14ce567518
Revises: 08808888a158
Create Date: 2026-07-29 08:46:38.998420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd14ce567518'
down_revision: Union[str, None] = '08808888a158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_pillar_insights',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('source_pillar', sa.String(length=30), nullable=False),
    sa.Column('target_pillar', sa.String(length=30), nullable=False),
    sa.Column('insight_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_pillar_insights_district'), 'cross_pillar_insights', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cross_pillar_insights_district'), table_name='cross_pillar_insights')
    op.drop_table('cross_pillar_insights')
    # ### end Alembic commands ###
